language: node_js
node_js:
  - '11.6'

cache:
  npm: true
  directories:
    - node_modules

script:
  - npm run lint
  - npm run coveralls

after_script:
  - "cat ./coverage/lcov.info | coveralls"

deploy:
  provider: npm
  email: $EMAIL
  api_key:
    secure: $API_KEY
  on:
    branch: master
    all_branches: false
    repo: joaaomanooel/bitcoin-converter-cli
