language: node_js
node_js:
  - '12.13'

cache:
  directories:
    - node_modules

script:
  - yarn lint
  - yarn coveralls

after_script:
  - "cat ./coverage/lcov.info | coveralls"

deploy:
  provider: npm
  email: $EMAIL
  api_key:
    secure: $API_KEY
  on:
    branch: master
    all_branches: false
    repo: joaaomanooel/bitcoin-converter-cli
