language: node_js
node_js:
  - node

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn lint
  - yarn coveralls

after_script:
  - "cat ./coverage/lcov.info | coveralls"

deploy:
  provider: npm
  email: $EMAIL
  api_key: $API_KEY
  on:
    branch: master
    all_branches: false
    repo: joaaomanooel/bitcoin-converter-cli
